### ISSUE TITLE
"TypeError: integer argument expected, got float" when using memcached

### ISSUE THREAD

**Issue by Directory** [pallets-eco/flask-caching#208]
```py
cache_config = {
    'CACHE_TYPE': 'memcached'
}
```
```py
Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/home/blank/env/lib/python3.8/site-packages/flask_caching/__init__.py", line 463, in decorated_function
    self.cache.set(
  File "/home/blank/env/lib/python3.8/site-packages/flask_caching/backends/memcache.py", line 141, in set
    return self._client.set(key, value, timeout)
TypeError: integer argument expected, got float
```
no additional config. memcached is installed on ubuntu server from apt with 0 additional configurations. pymemlib or whatever its called is installed and all of its dependencies are in check. the memcached systemd service is running. strangly this doesnt happen on all endpoints. it doesnt happen on those rendering html. just those returning json. heres an example of what the json contains.
`{"a":2,"b":{"c":0,"d":600}}`. could it be an issue related to serializing data? none of the values where floats just ints. but it should be able to handle anything. i also have it on an internal function (not a flask endpoint) that returns a python array of dictionarys and it also is working fine. just that 1 json endpoint.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one belongs in the cache backend client rather than this repo.

Evidence:
- The traceback points at `cachelib/memcache.py` (line 141 in the version reported): `return self._client.set(key, value, timeout)`. Flask-Caching's `MemcachedCache` doesn't override `set` and doesn't intercept the `timeout` value before forwarding to the memcached client.
- The memcached binary protocol expects an integer expiration; the client (`python-memcached`, `pymemcache`, or `libmc` depending on what you have installed) is what raises `TypeError: integer argument expected, got float` when handed a float. Whether to coerce a float to `int(timeout)` is a decision for cachelib + the underlying client driver.
- Workaround in your code today: pass `timeout=int(seconds)` (or `default_timeout=int(...)`). The issue is reproducible by passing a `timedelta.total_seconds()` literal without rounding.

If I'm wrong and there's a place in `flask_caching` (e.g. a `decorated_function.cache_timeout` math) where the float is introduced upstream, point me at the line and I'll dig further. Otherwise would you mind closing this out and reopening at [pallets-eco/cachelib](https://github.com/pallets-eco/cachelib/issues) with the proposal "coerce timeout to int in MemcachedCache.set"?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*

**Comment by john0isaac** [comment]
I'm not able to replicate this issue.
Is it still happening in latest flask-caching versions?

**Comment by sh4nks** [comment]
Feel free to re-open it if you still experience this issue. I am closing it now.
