### ISSUE TITLE
KeyError when initializing cache

### ISSUE THREAD

**Issue by dantebarba** [pallets-eco/flask-caching#322]
When initializing the Cache with SimpleCache it returns KeyError since it cannot find the Cache instance in the app extensions dict.

Create the app using a factory  _create_app.py:_

```python
cache = Cache()
def create_app():
    """Flask automatically detects the create_app functions"""
    # create flask app
    app = Flask(__name__)
    cache.init_app(app=app, config={'CACHE_TYPE': 'SimpleCache'})

   # register a blueprint
   from endpoints.zoho import zoho

   app.register_blueprint(api)
   return app


if __name__ == "__main__":
    create_app().run()
```

Blueprint code (where it fails) _api.py:_

```python
# ... rest of the imports go here
from create_app import cache 

api = Blueprint("api", __name__)

@buyer.route("/products")
@cache.cached(timeout=50, make_cache_key=make_cache_key)
@authorized
def get_products(user):
    result = Product.get_products(user)
    return jsonify(result), 200
```

When we fire a GET call to /products the end-result is the following stacktrace:

```python
{'mail': <flask_mail._Mail object at 0x10e352e90>, 'cache': {<flask_caching.Cache object at 0x10e21df50>: <flask_caching.backends.simplecache.SimpleCache object at 0x10e362450>}}**
[2022-03-08 23:45:31,935] ERROR in handlers: There was an error processing your request # uuid=af235abf-2a8e-4a68-b68d-09810d8474d2
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/flask_caching/__init__.py", line 452, in decorated_function
    rv = self.cache.get(cache_key)
  File "/venv/lib/python3.7/site-packages/flask_caching/__init__.py", line 260, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x10e381dd0>
```

Environment:

- Python version: python 3.7.12 running on venv
- Flask-Caching version: 1.10.0

**Comment by dantebarba** [comment]
Solved.

For those wondering how to solve this issue: 

cache variable should be refactored into a new module containing it. Then this module should be imported.

caching.py

```python
from flask_caching import Cache

cache = Cache()
```

create_app.py

```python
# imports here ...
from caching import cache

def create_app():
    """Flask automatically detects the create_app functions"""
    # create flask app
    app = Flask(__name__)
    cache.init_app(app=app, config={'CACHE_TYPE': 'SimpleCache'})

   # register a blueprint
   from endpoints.zoho import zoho

   app.register_blueprint(api)
   return app


if __name__ == "__main__":
    create_app().run()
```
