### ISSUE TITLE
flask-caching with RedisCache is incompatible with the use of flask.Reponse.on_close_call

### ISSUE THREAD

**Issue by ibeauregard** [pallets-eco/flask-caching#366]
Flask caching generates an error when trying to cache a response on which [on_close_call](https://flask.palletsprojects.com/en/2.1.x/api/#flask.Response.call_on_close) was invoked to add a callback to be invoked on response close.

The cache type used here is RedisCache.

The following view adds a callback to the response, to be invoked once the response has closed. This works as expected.

```python
@api.route('/')
def get_hi():
    response = Response('hi')
    response.call_on_close(lambda: None)
    return response
```

However, if I cache the response like so:

```python
@api.route('/')
@cache.cached()
def get_hi():
    response = Response('hi')
    response.call_on_close(lambda: None)
    return response
```

I get the following error:
```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 409, in decorated_function
    self.cache.set(
  File "/opt/venv/lib/python3.9/site-packages/cachelib/redis.py", line 97, in set
    dump = self.dump_object(value)
  File "/opt/venv/lib/python3.9/site-packages/flask_caching/backends/rediscache.py", line 106, in dump_object
    return b"!" + pickle.dumps(value)
AttributeError: Can't pickle local object 'get_hi.<locals>.<lambda>'
```

Expected behaviour: Caching of the response without any error.

Environment:

- Python version: 3.9.13
- Flask-Caching version: 1.11.1

**Comment by sidshrivastav** [comment]
I tried the same thing, it is throwing error for being not able to use local bound data

**Comment by john0isaac** [comment]
Thank you for reporting!
The issue here is that you are using a lambda function, lambda functions are not picklable.
Pickle stores a function by reference not by value. A lambda function inside a view has not importable name so you get the error `get_hi.<locals>.<lambda>` and pickling fails.
`flask-caching` is fully compatible with `call_on_close` if you use a module level function it will be pickled and the callback will fire with every cache hit.

Below is a working example:
```py
import logging

from flask import Flask
from flask import Response

from flask_caching import Cache

logger = logging.getLogger(__name__)

app = Flask(__name__)
cache = Cache(
    app,
    config={
        "CACHE_TYPE": "RedisCache",
        "CACHE_REDIS_URL": "redis://localhost:6360/0",
        "CACHE_DEFAULT_TIMEOUT": 10,
    },
)


def log_close() -> None:
    # Module level, pickled by reference, so the cached Response keeps it.
    logger.info("response closed")


@app.route("/")
@cache.cached()
def get_hi():
    response = Response("sv")
    response.call_on_close(log_close)
    return response


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5001)
```

Notice the function `log_close` not a lambda function.

@sh4nks you can close this one too as it's a limitation of `pickle` not `flask-caching` or `CacheLib `

@ibeauregard if you really want to cache it as is you can override CacheLib serializer and not use pickle in it instead use a library that handles this or write a special function to handle it.
