### ISSUE TITLE
Lock cachelib dependency version

### ISSUE THREAD

**Issue by Caetan95** [pallets-eco/flask-caching#381]
Hello, 

[version 1.11.1](https://flask-caching.readthedocs.io/en/latest/changelog.html#version-1-11-1) doesn't lock cachelib dependency version, so the latest one can have some breaking changes as the following

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/webservices_portal/wsgi.py", line 4, in <module>
app = create_app()
File "/usr/local/lib/python3.8/site-packages/webservices_portal/core/app.py", line 51, in create_app
cache.init_app(app)
File "/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py", line 141, in init_app
self._set_cache(app, config)
File "/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py", line 172, in _set_cache
app.extensions["cache"][self] = cache_factory(
File "/usr/local/lib/python3.8/site-packages/flask_caching/backends/rediscache.py", line 90, in factory
new_class = cls(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask_caching/backends/rediscache.py", line 62, in __init__
self._write_client = self._read_clients = self._client
AttributeError: 'RedisCache' object has no attribute '_client'
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by northernSage** [comment]
It was pinned in 2.0.0
