### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by udatsnoi** [pallets-eco/flask-caching#572]
I am using @cache decorator across my Flask=3.0.0 web application actively with Flask-Caching==2.2.0. In production I frequently see the following errors (not reproducible)

Example:
`@cache.cached(timeout=3600, key_prefix=make_cache_key)
`
```
2024-06-15 09:22:57,337: Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/python3.9/site-packages/flask_caching/__init__.py", line 420, in decorated_function
    self.cache.set(
  File "/python3.9/site-packages/cachelib/simple.py", line 79, in set
    self._prune()
  File "/python3.9/site-packages/cachelib/simple.py", line 56, in _prune
    self._remove_expired(now)
  File "/python3.9/site-packages/cachelib/simple.py", line 37, in _remove_expired
    toremove = [k for k, (expires, _) in self._cache.items() if expires < now]
  File "/python3.9/site-packages/cachelib/simple.py", line 37, in <listcomp>
    toremove = [k for k, (expires, _) in self._cache.items() if expires < now]
RuntimeError: dictionary keys changed during iteration
```

Since it is a decorator and I don't control pruning cache, I suspect there could be a bug in the library or its dependencies. Please advice. Happy to fix it myself here if you guide me to the potential problem.

**Comment by DarkRedman** [comment]
I got the exact same error and stacktrace, I think it's related to the fact Flask can be use with multithreading but that cachelib is not threadsafe.

I think the best solution is to use a lock either on cachelib or flask-caching

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this belongs at [`pallets-eco/cachelib`](https://github.com/pallets-eco/cachelib) rather than this repo.

Evidence:
- Your traceback ends at:
  ```
  File "/python3.9/site-packages/cachelib/simple.py", line 79, in set
      self._prune()
  File "/python3.9/site-packages/cachelib/simple.py", line ...
  RuntimeError: dictionary keys changed during iteration
  ```
  `cachelib.SimpleCache._prune` iterates over `self._cache` while modifying it. That's in cachelib, not in this repo. Flask-Caching just wraps cachelib's `SimpleCache` ([`src/flask_caching/backends/simplecache.py`](https://github.com/pallets-eco/flask-caching/blob/main/src/flask_caching/backends/simplecache.py)) and does not override `_prune` / `set`.
- The "not reproducible" nature in production fits a concurrent-write race in `_prune`, which is a class of bug that needs to be fixed in cachelib's iteration code.

If I'm wrong and you see a `_prune` override in `flask_caching`, please point me at the line. Otherwise would you mind closing this out and filing at [pallets-eco/cachelib](https://github.com/pallets-eco/cachelib/issues) with the traceback? The cachelib team can guard the iteration with `list(self._cache.items())` or a lock there.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*

**Comment by sh4nks** [comment]
I believe this should fix it: https://github.com/pallets-eco/cachelib/pull/461
